import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { MakeswiftComponent } from '@makeswift/runtime/next'
import { getSiteVersion } from '@makeswift/runtime/next/server'

import { CHAT_WIDGET_COMPONENT_TYPE } from '@/components/MosqueChatWidget/MosqueChatWidget.makeswift'
import { client } from '@/lib/makeswift/client'
import '@/lib/makeswift/components'
import { MakeswiftProvider } from '@/lib/makeswift/provider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const siteVersion = await getSiteVersion()

  const chatWidgetSnapshot = await client.getComponentSnapshot(
    'mosque-chat-widget',
    { siteVersion }
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        <MakeswiftProvider siteVersion={siteVersion}>
          {children}
          <MakeswiftComponent
            snapshot={chatWidgetSnapshot}
            label="Mosque Chat Widget"
            type={CHAT_WIDGET_COMPONENT_TYPE}
          />
        </MakeswiftProvider>
      </body>
    </html>
  )
}
