import '@/components/Accordions/Accordions.makeswift'
import '@/components/Button/Button.makeswift'
import '@/components/Calendar/Calendar.makeswift'
import '@/components/Input/Input.makeswift'
import '@/components/Marquee/Marquee.makeswift'
import '@/components/Tabs/Tabs.makeswift'
